export const GET_CONTRACTS_BY_ID_REQUESTING = 'GET_CONTRACTS_BY_ID_REQUESTING'
export const GET_CONTRACTS_BY_ID_ERROR = 'GET_CONTRACTS_BY_ID_ERROR'
export const GET_CONTRACTS_BY_ID_SUCCESS = 'GET_CONTRACTS_BY_ID_SUCCESS'

export const GET_ALL_CONTRACTS_REQUESTING = 'GET_ALL_CONTRACTS_REQUESTING'
export const GET_ALL_CONTRACTS_ERROR = 'GET_ALL_CONTRACTS_ERROR'
export const GET_ALL_CONTRACTS_SUCCESS = 'GET_ALL_CONTRACTS_SUCCESS'

export const GET_UNPAID_JOBS_REQUESTING = 'GET_UNPAID_JOBS_REQUESTING'
export const GET_UNPAID_JOBS_ERROR = 'GET_UNPAID_JOBS_ERROR'
export const GET_UNPAID_JOBS_SUCCESS = 'GET_UNPAID_JOBS_SUCCESS'

export const PAY_JOB_REQUESTING = 'PAY_JOB_REQUESTING'
export const PAY_JOB_ERROR = 'PAY_JOB_ERROR'
export const PAY_JOB_SUCCESS = 'PAY_JOB_SUCCESS'

export const DEPOSIT_MONEY_REQUESTING = 'DEPOSIT_MONEY_REQUESTING'
export const DEPOSIT_MONEY_ERROR = 'DEPOSIT_MONEY_ERROR'
export const DEPOSIT_MONEY_SUCCESS = 'DEPOSIT_MONEY_SUCCESS'

export const GET_BEST_PROFESSION_REQUESTING = 'GET_BEST_PROFESSION_REQUESTING'
export const GET_BEST_PROFESSION_ERROR = 'GET_BEST_PROFESSION_ERROR'
export const GET_BEST_PROFESSION_SUCCESS = 'GET_BEST_PROFESSION_SUCCESS'

export const GET_BEST_CLIENTS_REQUESTING = 'GET_BEST_CLIENTS_REQUESTING'
export const GET_BEST_CLIENTS_ERROR = 'GET_BEST_CLIENTS_ERROR'
export const GET_BEST_CLIENTS_SUCCESS = 'GET_BEST_CLIENTS_SUCCESS'